name: vnc-sim
channels:
  - conda-forge
dependencies:
  - jupyter
  - matplotlib
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - omegaconf
  - sparse
  - pip
  - pip:
    - "--editable=."
    - hydra-core
    - diffrax
    - jax[cuda12]
    - h5py
    - natsort
    - nvidia-ml-py3
    - tqdm
    - pynvml
    - psutil
