name: bdn2cpg
channels:
  - conda-forge
dependencies:
  - jupyter
  - matplotlib
  - numba
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - seaborn
  - omegaconf
  - pip
  - pip:
    - "--editable=."
    - hydra-core
    - jax[cuda12]