user: denis.turcu

# set the directory where the output files get saved
cwd_dir:  /Users/${paths.user}/Library/CloudStorage/OneDrive-AllenInstitute/projects/Pugliese_2025/
base_dir: /Users/${paths.user}/Library/CloudStorage/OneDrive-AllenInstitute/projects/Pugliese_2025/${experiment.name}/${version}
save_dir: ${paths.base_dir}/run_id=${run_id}/
log_dir:  ${paths.save_dir}/logs/
ckpt_dir: ${paths.save_dir}/ckpt/
fig_dir:  ${paths.save_dir}/figures/
data_dir: /Users/${paths.user}/Library/CloudStorage/OneDrive-AllenInstitute/projects/Pugliese_2025/data