user: eabe

# set the directory where the output files get saved
cwd_dir:  /gscratch/portia/${paths.user}/Research/Github/Pugliese_2025/
base_dir: /gscratch/portia/${paths.user}/Pugliese_2025/${experiment.name}/${version}
save_dir: ${oc.select:hydra.runtime.output_dir,${fallback_path:${paths.base_dir},${oc.select:run_id,null}}}
log_dir:  ${paths.save_dir}/logs/
ckpt_dir: ${paths.save_dir}/ckpt/
fig_dir:  ${paths.save_dir}/figures/
data_dir: /gscratch/portia/${paths.user}/Research/Github/Pugliese_2025/data