user: jkl

# set the directory where the output files get saved
cwd_dir:  /home/${paths.user}/Pugliese_2025/
base_dir: /data/users/smpuglie/Pugliese_2025/${experiment.name}/${version}
save_dir: ${paths.base_dir}/run_id=${run_id}/
log_dir:  ${paths.save_dir}/logs/
ckpt_dir: ${paths.save_dir}/ckpt/
fig_dir:  ${paths.save_dir}/figures/
data_dir: /home/${paths.user}/Pugliese_2025/data