##### Easy Access Variables #####
# if set to positive integer, overrides the default
version: 'debug' # stim-replicates
seed: None
num_gpus: ''
run_id: 'walle'
load_jobid: ''
note: ''
ckpt_list: []

# set default task and default training config based on dataset
defaults:
  - _self_
  - experiment: stim_neurons
  - neuron_params: default
  - paths: walle-smpuglie
  - sim: default


# set the directory where the output files get saved
hydra:
  job:
      config:
        override_dirname:
          exclude_keys:
            - paths
            - version
            - dataset
            - run_id
            - experiment
            - sim
            - neuron_params

  run:
    dir: ${paths.base_dir}/run_id=${run_id}
  sweep:
    dir: ${paths.base_dir}/run_id=${run_id}
    subdir: ${hydra.job.override_dirname}