# Default configuration for the simulation
name: TestingSimulationParams

T: 2.0
dt: 0.001
pulseStart: 0.02
pulseEnd: 1.999
adjustStimI: False
maxIters: 10
nActiveUpper: 500
nActiveLower: 5
nHighFrUpper: 100
shuffle: False
noise: False
noiseStdvProp: 0.1
